version: '3.1'
services:
  api:
    build: .
    image: tree-app:latest
    ports:
      - "8084:8084"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tree-app
      POSTGRES_PASSWORD: tree-app
      POSTGRES_DB: tree-app