spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://postgresdb:5432/tree-app
    username: tree-app
    password: tree-app

server:
  servlet:
    context-path: /api/v1
  port: 8084
